sudo: false

language: cpp

os:
    - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - gcc-4.8
      - g++-4.8

cache:
    directories:
      - sconsCache
      - pyIlmBaseInstall

install:
    - if [ -n "$COMPILER_VERSION" ]; then export CXX="${CXX}-${COMPILER_VERSION}"; fi
    - python ./config/travis/installDependencies.py
    - export DEPENDENCIES=`pwd`/dependencies

script:
    # Preload libSegFault when running tests, so we get stack
    # traces from any crashes.
    - export LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - export LD_LIBRARY_PATH=$DEPENDENCIES/lib
    - scons -j 2
      testCore testCorePython testScene
      CXX=$CXX
      CXXSTD=$CXXSTD
      BOOST_INCLUDE_PATH=$DEPENDENCIES/include
      PYTHON=$DEPENDENCIES/bin/python
      PYTHON_INCLUDE_PATH=$DEPENDENCIES/include/python2.7
      PYTHON_LINK_FLAGS=-lpython2.7
      LIBPATH=$DEPENDENCIES/lib
      PYTHONPATH=$DEPENDENCIES/lib/python2.7/site-packages
      DEBUG=$DEBUG
      ENV_VARS_TO_IMPORT="PATH TRAVIS LD_PRELOAD LD_LIBRARY_PATH"
      RMAN_ROOT=$DELIGHT
      BOOST_LIB_SUFFIX=""
      BUILD_CACHEDIR=sconsCache
    - cat test/IECore/results.txt

before_cache:
    # This is run just before uploading the cache for next time.
    # SCons caches grow without bound so we want to remove old
    # files to prevent our caches becoming too big.
    - python ./config/travis/limitCacheSize.py
    - du -sh sconsCache

# Default values for environment variables we use to
# control the build.
env:
    - COMPILER_VERSION= CXXSTD=c++98 DEBUG=0

compiler:
    ## \todo Enable clang here too. We can't with the default Ubuntu boost
    # install though, because it is broken for Clang :
    #
    # https://svn.boost.org/trac/boost/ticket/6156
    - gcc

matrix:
    # Explicit list of all permutations of environment
    # and compiler we want to test. These are on top
    # of the defaults provided above.
    include:
        - os: linux
          compiler: gcc
          env: COMPILER_VERSION=4.8 CXXSTD=c++11 DEBUG=0
        - os: linux
          compiler: gcc
          env: COMPILER_VERSION=4.8 CXXSTD=c++11 DEBUG=1

